import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PageHeader from '@/components/page-header'
import Sidebar from '@/components/side-bar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sophia Health',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative items-center justify-center">
          <PageHeader />
        </div>
        <div>
          <Sidebar />
        </div>
        {children}
      </body>
    </html>
  )
}
