import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PageHeader from '@/components/page-header'
import Sidebar from '@/components/side-bar'
import CardWithForm from '@/components/note-generator/soap-element-card'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sophia Health',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <div className="flex h-screen flex-col">
            <PageHeader />
            <div className="flex flex-grow overflow-auto">
              <Sidebar />
              {children}
            </div>
          </div>
          <div className="flex">
            <Sidebar />
            {children}
          </div>
        </ClerkProvider>
      </body>
    </html>
  )
}
